# Generated by Django 6.1.1 on 2026-09-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_rule', models.CharField(choices=[('>', 'x·y > 0 (green if >)'), ('<', 'x·y < 0 (green if <)')], default='>', help_text='Label rule for product dataset: ">" means label=1 if x*y>0 else 0; "<" inverts.', max_length=2)),
                ('center_x', models.FloatField(default=0.0, help_text='Dataset center X (translation after rotation).')),
                ('center_y', models.FloatField(default=0.0, help_text='Dataset center Y (translation after rotation).')),
                ('rotation', models.FloatField(default=0.0, help_text='Rotation in degrees (counter-clockwise) applied to (rx,ry) before shifting by center.')),
                ('file_path', models.CharField(blank=True, default='', help_text='Filesystem path to the persisted torch model (e.g. torch.save state_dict).', max_length=512)),
                ('create_on', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp.')),
                ('update_on', models.DateTimeField(auto_now=True, help_text='Last update timestamp.')),
            ],
            options={
                'verbose_name': 'MLP model',
                'verbose_name_plural': 'MLP models',
                'ordering': ['-create_on'],
            },
        ),
    ]
